### ISSUE TITLE
Graphviz-react not imported correctly with create-react-app default jest configuration

### ISSUE THREAD

**Issue by jake-goldsmith** [DomParfitt/graphviz-react#83]
I am unable to run jest tests in a create-react-app project using graphviz-react 1.2.5.

Steps to reproduce:

1. `npx create-react-app graphviz-test --template typescript`
2. `cd graphviz-test`
3. `npm install graphviz-react`
4. Amend the default App.tsx file as follows 

```
import React from 'react';
import logo from './logo.svg';
import './App.css';
import { Graphviz } from "graphviz-react";

function App() {
    return (
        <div className="App">
            <header className="App-header">
                <img src={logo} className="App-logo" alt="logo"/>
                <p>
                    Edit <code>src/App.tsx</code> and save to reload.
                </p>
                <a
                    className="App-link"
                    href="https://reactjs.org"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Learn React
                </a>
                <Graphviz dot={`graph {
                  grandparent -- "parent A";
                  child;
                  "parent B" -- child;
                  grandparent --  "parent B";
                }`}/>
            </header>
        </div>
    );
}

export default App;
```

Output of `npm run test`:
```
> graphviz-test@0.1.0 test
> react-scripts test
 FAIL  src/App.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    path-to-project/graphviz-test/node_modules/graphviz-react/lib/Graphviz.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import * as React from 'react';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      2 | import logo from './logo.svg';
      3 | import './App.css';
    > 4 | import { Graphviz } from "graphviz-react";
        | ^
      5 |
      6 | function App() {
      7 |   return (

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/App.tsx:4:1)
      at Object.<anonymous> (src/App.test.tsx:3:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)

```

Possibly I could change something in the [configuration](https://create-react-app.dev/docs/running-tests/#configuration) but I wasn't able to work it out. 

Note: The project does run correctly now when running `npm run start` so the issue is definitely with the jest config particularly. Thanks!

**Comment by DomParfitt** [comment]
I think this might be a more general issue with Jest and how it handles ES modules (which is what this package outputs), rather than an issue with this package.

However there is a workaround for this by using the `transformIgnorePatterns` to ignore this package. If you add this to your `package.json` then it should solve the issue :
```json
"jest": {
  "transformIgnorePatterns": [
    "node_modules/(?!(graphviz-react)/)"
  ]
}
```

You may also hit an error along the lines of : `TypeError: element.node(...).getTotalLength is not a function`, which is because `jsdom` (which `create-react-app` uses by default to render components in tests) doesn't fully implement [SVG elements](https://github.com/jsdom/jsdom/issues/1330), which is what is used to render the graph. You should be able to work around this by adding this snippet to any tests that render the `Graphviz` component (either directly or indirectly) to mock out the missing functionality from `jsdom`:
```js
beforeAll(() => {
  SVGElement.prototype.getTotalLength = jest.fn();
});
```

**Comment by jake-goldsmith** [comment]
Thank you, that completely fixes the issue. Cheers! I did not realise graphviz-react output an ES module.
